local RE4R_MaterialData = {
    wp4000 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4000_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4001 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4002 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4002_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4003 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4004 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4100 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4100_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4101 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4101_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4102 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4200 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4200_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4201 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4201_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4202 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4202_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4400 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4400_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4401 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4401_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4402 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4500 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4500_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4501 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4501_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4502 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4600 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4900 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp4902 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5000 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5000_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5001 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5001_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5006 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5400 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5400_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5401 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5401_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5402 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5402_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5403 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5404 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp5405 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6000 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6001 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6100 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6100_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6101 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6102 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6102_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6103 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6103_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6104 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6104_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6105 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6105_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6106 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6107 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6107_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6108 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6111 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6112_AO = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6113_AO = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6114 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6300_MC = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
    wp6304 = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
        Materials = {},
        MeshPath = "",
        MDFPath = "",
        MeshName = "",
    },
}

return RE4R_MaterialData