local RE8_MaterialData = {
    ri3008_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3021_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3023_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3036_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3040_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3042_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3046_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3047_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3048_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3049_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3050_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3115_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3116_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3122_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3124_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3125_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3135_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3147_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3081_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3082_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3083_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3084_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3085_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3086_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3087_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3129_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
    ri3130_Inventory = {
        Presets = {},
        current_preset_indx = 1,
        Parts = {},
        Enabled = {},
    },
}
return RE8_MaterialData