local RE2R_LanguageData = {
    Languages = {
        [1] = "EN",
        [2] = "JA",
        [3] = "FR",
        [4] = "IT",
        [5] = "DE",
        [6] = "ES",
        [7] = "RU",
        [8] = "PL",
        [9] = "PTBR",
        [10] = "ZHTW",
        [11] = "ZHCN",
        [12] = "KO",
        [13] = "AR",
        [14] = "TH",
        [15] = "ESLATAM",
    },
    wp0000 = {
        isUpdated = false,
        isForceEN = false,
        isUseSpecialStyle = false,
        current_preset_indx = 1,
        current_language_indx = 1,
        Presets = {},
        Name = {
            Style = {
                isInheritMainColor = false,
                _Position = {14.0, 9.0, 0.0},
                _Rotation = {0.0, 0.0, 0.0},
                _FontSlot = 1,
                _FontSize = {
                    w = 24.0,
                    h = 24.0,
                },
                _PageAlignment = 4,
                _LetterAlignment = 0,
                _LetterSpace = 0.0,
                _LineSpace = 0.0,
                _AutoWrap = false,
                _ForceAutoWrap = false,
                _AutoEraseHeadSpace = false,
                _AutoRegionFit = 0,
                _AutoRTL = true,
                _AutoArabicLayout = false,
                _Kerning = false,
                _Monospace = false,
                _VerticalLayout = false,
                _Italic = false,
                _Bold = false,
                _Color ={255, 252, 235, 255},
                _ColorTop = {255, 252, 235, 255},
                _ColorBottom = {255, 255, 255, 255},
                _GlowEnable = false,
                _GlowInner = false,
                _GlowKnockout = false,
                _GlowBlurSize = {
                    w = 5.0,
                    h = 5.0,
                },
                _GlowStrength = 1.0,
                _GlowColor = {255, 252, 235, 255},
                _ShadowEnable = true,
                _ShadowBlurSize = {
                    w = 10.0,
                    h = 10.0,
                },
                _ShadowStrength = 3.0,
                _ShadowRotation = 30.0,
                _ShadowDistance = 0.0,
                _ShadowDistanceZ = 0.1,
                _ShadowColor = {0, 0, 0, 179}

            },
            Language = {
                EN = "Matilda",
                JA = "マチルダ",
                FR = "Matilda",
                IT = "Matilda",
                DE = "Matilda",
                ES = "Matilda",
                RU = "Матильда",
                PL = "Matilda",
                PTBR = "Matilda",
                ZHTW = "瑪蒂達",
                ZHCN = "玛蒂尔达",
                KO = "마틸다",
                AR = "ماتيلدا",
                TH = "Matilda",
                ESLATAM = "Matilda",
            },
        },
        Category = {
            Style = {
                isInheritMainColor = false,
                _Position = {14.0, 42.0, 0.0},
                _Rotation = {0.0, 0.0, 0.0},
                _FontSlot = 2,
                _FontSize = {
                    w = 20.0,
                    h = 20.0,
                },
                _PageAlignment = 4,
                _LetterAlignment = 0,
                _LetterSpace = 0.0,
                _LineSpace = 0.0,
                _AutoWrap = false,
                _ForceAutoWrap = false,
                _AutoEraseHeadSpace = false,
                _AutoRegionFit = 0,
                _AutoRTL = true,
                _AutoArabicLayout = false,
                _Kerning = false,
                _Monospace = false,
                _VerticalLayout = false,
                _Italic = false,
                _Bold = false,
                _Color = {151, 151, 143, 255},
                _ColorTop = {151, 151, 143, 255},
                _ColorBottom = {151, 151, 143, 255},
                _GlowEnable = false,
                _GlowInner = false,
                _GlowKnockout = false,
                _GlowBlurSize = {
                    w = 5.0,
                    h = 5.0,
                },
                _GlowStrength = 1.0,
                _GlowColor = {255, 255, 225, 255},
                _ShadowEnable = true,
                _ShadowBlurSize = {
                    w = 10.0,
                    h = 10.0,
                },
                _ShadowStrength = 3.0,
                _ShadowRotation = 30.0,
                _ShadowDistance = 0.0,
                _ShadowDistanceZ = 0.1,
                _ShadowColor = {0, 0, 0, 179}
            },
            Language = {
                EN = "Handgun",
                JA = "ハンドガン",
                FR = "Arme de poing",
                IT = "Pistola",
                DE = "Pistole",
                ES = "Pistola",
                RU = "Пистолет",
                PL = "Pistolet",
                PTBR = "Pistola",
                ZHTW = "手槍",
                ZHCN = "手枪",
                KO = "권총",
                AR = "مسدس",
                TH = "ปืนพก",
                ESLATAM = "Pistola",
            },
        },
        Detail = {
            Style = {
                isInheritMainColor = false,
                _Position = {14.0, 81.0, 0.0},
                _Rotation = {0.0, 0.0, 0.0},
                _FontSlot = 2,
                _FontSize = {
                    w = 23.0,
                    h = 23.0,
                },
                _PageAlignment = 0,
                _LetterAlignment = 0,
                _LetterSpace = 2.0,
                _LineSpace = 0.0,
                _AutoWrap = false,
                _ForceAutoWrap = false,
                _AutoEraseHeadSpace = false,
                _AutoRegionFit = 0,
                _AutoRTL = true,
                _AutoArabicLayout = false,
                _Kerning = false,
                _Monospace = false,
                _VerticalLayout = false,
                _Italic = false,
                _Bold = false,
                _Color = {199, 199, 185, 255},
                _ColorTop = {199, 199, 185, 255},
                _ColorBottom = {255, 255, 255, 255},
                _GlowEnable = false,
                _GlowInner = false,
                _GlowKnockout = false,
                _GlowBlurSize = {
                    w = 5.0,
                    h = 5.0,
                },
                _GlowStrength = 1.0,
                _GlowColor = {199, 199, 185, 255},
                _ShadowEnable = true,
                _ShadowBlurSize = {
                    w = 10.0,
                    h = 10.0,
                },
                _ShadowStrength = 3.0,
                _ShadowRotation = 30.0,
                _ShadowDistance = 0.0,
                _ShadowDistanceZ = 0.1,
                _ShadowColor = {0, 0, 0, 179}

            },
            Language = {
                EN = "12-shot capacity 9mm polymer\r\nframe handgun. Non-standard issue\r\ngun with problems that make it\r\nimpractical for the general public.",
                JA = "9mm弾を12発装填できる、\r\nポリマー製フレームのハンドガン。\r\n国民拳銃を目指すが実用面での問題が多く、\r\n公式装備にはいたらなかった。",
                FR = "Un pistolet en polymère. De nombreux\r\ndéfauts l'ont rendu peu adapté pour les\r\ncivils ou les forces de l'ordre.\r\nCapacité : 12 coups (9 mm)",
                IT = "Pistola con struttura in polimeri\r\nda 9mm a 12 colpi. Pistola di\r\nordinanza non standard, poco\r\npratica per i civili.",
                DE = "9-mm-Polymerpistole mit 12 Schuss.\r\nAufgrund einiger Probleme in der\r\nHandhabung hat sie sich nicht als \r\nStandardausrüstung etabliert.",
                ES = "Pistola de armazón de polímero\r\ncon 12 balas de 9mm. Arma\r\nno reglamentaria con problemas,\r\npoco práctica para el uso general.",
                RU = "12-зарядный пистолет с полимерным\r\nкорпусом калибра 9мм. Обладает\r\nрядом недостатков, поэтому не был\r\nзапущен в массовое производство.",
                PL = "Pistolet polimerowy kal. 9 mm\r\nz magazynkiem o pojemności 12 nab.\r\nNiestandardowy model, którego wady\r\nsprawiają, że jest niepraktyczny.",
                PTBR = "Pistola 9 mm em polímero e\r\ncapacidade para 12 tiros. Edição\r\nnão padrão, tem problemas que a\r\ninviabilizam para o público geral.",
                ZHTW = "可裝 12 發子彈的 9 毫米\r\n聚合物材質手槍。由於其本身的\r\n一些問題，這把非制式武器並\r\n不適合一般民眾使用。",
                ZHCN = "可装填 12 发子弹的 \r\n9 毫米聚合物材质非标制式手枪，\r\n由于有些问题，所以不适合一般民众使用。",
                KO = "12발식 장전 9mm 폴리머\r\n프레임 권총. 비표준형 총으로,\r\n일반 대중의 사용이 불가능하다는\r\n단점이 있습니다.",
                AR = "هيكل بوليمر لمسدس سعة 12 طلقة\r\nمن عيار 9مم مسدس إصدار غير قياسي\r\nبه مشاكل تجعله\r\nغير عملي لعامة الناس.",
                TH = "ปืนพก 9 มม. ความจุ 12 นัด\r\nกรอบพอลิเมอร์ ปืนรุ่นนอกมาตรฐาน\r\nที่มีปัญหาซึ่งทำให้มันไม่เหมาะกับ\r\nการวางจำหน่ายทั่วไป",
                ESLATAM = "Pistola de armazón de polímero\r\ncon 12 balas de 9 mm. Arma\r\nno reglamentaria con problemas,\r\npoco práctica para el uso general.",
            }
        },
    },
}
return RE2R_LanguageData