local RE2R_LaserData = {
    wp0000 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp0100 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp0200 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle3",
    },
    wp0300 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp0600 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp0700 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp0800 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp1000 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp2000 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp2200 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp3000 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4100 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4200 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4300 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4400 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4600 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp4700 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp7000 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp7010 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp7020 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp7030 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp8400 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
    wp8700 = {
        isEnabled = false,
        isReticleEnabled = false,
        PartNum = 7652,
        HideAngle = 15.0,
        ShowAngle = 2.0,
        HideLength = 0.8,
        ShowLength = 4.0,
        SightEmitJointName = "vfx_muzzle1",
    },
}
return RE2R_LaserData