local RE7_WeaponData = {
    Weapons = {
        M19         =   {ID = "wp1010_Handgun_Item",                Name = "M19 Handgun",                   Type = "HG"},
        M21         =   {ID = "wp1030_Shotgun_Item",                Name = "M21 Shotgun",                   Type = "SG"},
        BR          =   {ID = "wp1000_GasBurner_Item",              Name = "Burner",                        Type = "FT"},
        GL          =   {ID = "wp1110_PortableCannon_Item",         Name = "Grenade Launcher",              Type = "GL"},
        MAG44       =   {ID = "wp1140_Magnum_Item",                 Name = "44 MAG",                        Type = "MAG"},
        P19         =   {ID = "wp1160_MachineGun_Item",             Name = "P19 Machine Gun",               Type = "SMG"},
        G17         =   {ID = "wp1210_Handgun_Item",                Name = "G17 Handgun",                   Type = "HG"},
        M37         =   {ID = "wp1230_PumpShotgun_Item",            Name = "M37 Shotgun",                   Type = "SG"},
        MPM         =   {ID = "wp1240_MiaHandgun_Item",             Name = "MPM Handgun",                   Type = "HG"},
        AW01        =   {ID = "wp1340_ChrisHandgun_Item",           Name = "Samurai Edge - AW Model-01",    Type = "HG"},
        AW02        =   {ID = "wp1330_ChrisShotgun_Item",           Name = "Thor's Hammer - AW Model-02",   Type = "SG"},
        AW01R       =   {ID = "wp1340_ChrisHandgun_Reward_Item",    Name = "Albert-01R",                    Type = "HG"},
        M21EOZ      =   {ID = "wp1033_Shotgun_Item",                Name = "M21 Shotgun - End of Zoe",      Type = "SG"},
        KNF_AXE     =   {ID = "wp0040_Axe_Item",                    Name = "Axe",                           Type = "KNF"},
        KNF_E       =   {ID = "wp1190_Knife_Item",                  Name = "Knife - Ethan",                 Type = "KNF"},
        KNF_M       =   {ID = "wp1360_MiaKnife_Item",               Name = "Knife - Mia",                   Type = "KNF"},
        KNF_C       =   {ID = "wp1390_ChrisKnife_Item",             Name = "Knife - Chris",                 Type = "KNF"},
        ----------------------------------------------------------------------------------------------------------------------
        FT_Ammo     =   {ID = "wp1001_GasCan_Item",                 Name = "Burner Fuel",                   Type = "Ammo"},
        HG_Ammo     =   {ID = "wp1011_HandgunBullet_Item",          Name = "Handgun Ammo",                  Type = "Ammo"},
        EX_HG_Ammo  =   {ID = "wp1013_HandgunBulletStrong_Item",    Name = "Enhanced Handgun Ammo",         Type = "Ammo"},
        SG_Ammo     =   {ID = "wp1031_ShotgunBullet_Item",          Name = "Shotgun Shells",                Type = "Ammo"},
        GL_F_Ammo   =   {ID = "wp1111_FlameBullet_Item",            Name = "Flame Rounds",                  Type = "Ammo"},
        GL_A_Ammo   =   {ID = "wp1112_AcidBullet_Item",             Name = "Neuro Rounds",                  Type = "Ammo"},
        MAG_Ammo    =   {ID = "wp1141_MagnumBullet_Item",           Name = "Magnum Ammo",                   Type = "Ammo"},
        SMG_Ammo    =   {ID = "wp1161_MachineGunBullet_Item",       Name = "Machine Gun Ammo",              Type = "Ammo"},
    },
    Weapon_Params = {
        wp1010_Handgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            LoadNum = 7,
            MaxLoadNum = 7,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.03,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0,
        },
        wp1030_Shotgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 2,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 20.0,
            AttenuationEnd = 30.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 7,
            DiffusionRadius = 0.08,
            AimDiffusionRadius = 0.05,
            RecoilBurstInterval = 0.5,
            RecoilBurstCount = 0,
            RecoilYAngle = 2.0,
            RecoilXAngle = 0.5
        },
        wp1000_GasBurner_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 150,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 5.0,
            AttenuationStart = 1.0,
            AttenuationEnd = 5.0,
            MinAttenuationDamageRate = 0.8,
            Radius = 0.2,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1110_PortableCannon_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 1,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1140_Magnum_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 7,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.15,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1160_MachineGun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 64,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.125,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.3,
            RecoilBurstCount = 1,
            RecoilYAngle = 1.750,
            RecoilXAngle = 0.5
        },
        wp1210_Handgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 10,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.01,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1230_PumpShotgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 4,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 20.0,
            AttenuationEnd = 30.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 7,
            DiffusionRadius = 0.15,
            AimDiffusionRadius = 0.12,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 1,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1240_MiaHandgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 9,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.06,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1330_ChrisShotgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 12,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 5.0,
            AttenuationEnd = 30.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 4,
            DiffusionRadius = 0.2,
            AimDiffusionRadius = 0.2,
            RecoilBurstInterval = 0.5,
            RecoilBurstCount = 1,
            RecoilYAngle = 2.0,
            RecoilXAngle = 0.5
        },
        wp1340_ChrisHandgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 9,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 0,
            DiffusionRadius = 0.5,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount = 3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1340_ChrisHandgun_Reward_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 3,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 30.0,
            AttenuationEnd = 50.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.01,
            DiffusionNum = 0,
            DiffusionRadius = 0.0,
            AimDiffusionRadius = 0.0,
            RecoilBurstInterval = 0.1,
            RecoilBurstCount =3,
            RecoilYAngle = 0.0,
            RecoilXAngle = 0.0
        },
        wp1033_Shotgun_Item = {
            Weapon_Presets = {},
            current_param_indx = 1,
            MaxLoadNum = 2,
            IsLoadNumInfinity = false,
            IsBulletStackNumInfinity = false,
            Range = 100.0,
            AttenuationStart = 20.0,
            AttenuationEnd = 30.0,
            MinAttenuationDamageRate = 0.5,
            Radius = 0.05,
            DiffusionNum = 7,
            DiffusionRadius = 0.08,
            AimDiffusionRadius = 0.05,
            RecoilBurstInterval = 0.5,
            RecoilBurstCount = 0,
            RecoilYAngle = 2.0,
            RecoilXAngle = 0.5
        },
    },
    Ammo_Params = {
        wp1001_GasCan_Item = {
            MaxStackNum = 500,
        },
        wp1011_HandgunBullet_Item = {
            MaxStackNum = 30,
        },
        wp1013_HandgunBulletStrong_Item = {
            MaxStackNum = 20,
        },
        wp1031_ShotgunBullet_Item = {
            MaxStackNum = 30,
        },
        wp1111_FlameBullet_Item = {
            MaxStackNum = 5,
        },
        wp1112_AcidBullet_Item = {
            MaxStackNum = 5,
        },
        wp1141_MagnumBullet_Item = {
            MaxStackNum = 20,
        },
        wp1161_MachineGunBullet_Item = {
            MaxStackNum = 300,
        },
    },
    Weapon_Order = {
        "G17",
        "M19",
        "MPM",
        "AW01R",
        "MAG44",
        "M21",
        "M21EOZ",
        "M37",
        "P19",
        "BR",
        "GL",
        "AW01",
        "AW02",
        "KNF_E",
        "KNF_M",
        "KNF_C",
        "KNF_AXE",
        "HG_Ammo",
        "EX_HG_Ammo",
        "SG_Ammo",
        "MAG_Ammo",
        "SMG_Ammo",
        "GL_F_Ammo",
        "GL_A_Ammo",
        "FT_Ammo",
    },
}

return RE7_WeaponData