local RE8_WeaponData = {
    Weapons = {
        M1851   =   {ID = "ri3008_Inventory",   Name = "M1851 Wolfsbane",               Type = "MAG"},
        W870    =   {ID = "ri3021_Inventory",   Name = "W870 TAC",                      Type = "SG"},
        GM79    =   {ID = "ri3023_Inventory",   Name = "GM 79",                         Type = "GL"},
        M1897   =   {ID = "ri3036_Inventory",   Name = "M1897",                         Type = "SG"},
        M1911   =   {ID = "ri3040_Inventory",   Name = "M1911",                         Type = "HG"},
        F2      =   {ID = "ri3042_Inventory",   Name = "F2 Rifle",                      Type = "SR"},
        LEMI    =   {ID = "ri3046_Inventory",   Name = "LEMI",                          Type = "HG"},
        V61     =   {ID = "ri3047_Inventory",   Name = "V61 Custom",                    Type = "HG"},
        SYG12   =   {ID = "ri3048_Inventory",   Name = "SYG-12",                        Type = "SG"},
        WCX     =   {ID = "ri3049_Inventory",   Name = "WCX",                           Type = "AR"},
        STK     =   {ID = "ri3050_Inventory",   Name = "S.T.A.K.E",                     Type = "MAG"},
        GYRO    =   {ID = "ri3115_Inventory",   Name = "Rocket Pistol",                 Type = "HG"},
        HCPZ    =   {ID = "ri3116_Inventory",   Name = "Handcannon PZ",                 Type = "MAG"},
        AW01    =   {ID = "ri3122_Inventory",   Name = "Samurai Edge - AW Model-01",    Type = "HG"},
        USMAI   =   {ID = "ri3124_Inventory",   Name = "USM-AI",                        Type = "HG"},
        DRGOO   =   {ID = "ri3125_Inventory",   Name = "Dragoon",                       Type = "AR"},
        ------------------------------------------------------------------------------------------------SOR
        LEMISOR =   {ID = "ri3135_Inventory",   Name = "LEMI - Shadows of Rose",        Type = "HG"},
        M1897SOR=   {ID = "ri3147_Inventory",   Name = "M1897 - Shadows of Rose",       Type = "SG"},
        ------------------------------------------------------------------------------------------------MC
        LEMIMC  =   {ID = "ri3081_Inventory",   Name = "LEMI - Mercenaries",            Type = "HG"},
        M1911MC =   {ID = "ri3082_Inventory",   Name = "M1911 - Mercenaries",           Type = "HG"},
        V61MC   =   {ID = "ri3083_Inventory",   Name = "V61 Custom - Mercenaries",      Type = "HG"},
        M1897MC =   {ID = "ri3084_Inventory",   Name = "M1897 - Mercenaries",           Type = "SG"},
        W870MC  =   {ID = "ri3085_Inventory",   Name = "W870 TAC - Mercenaries",        Type = "SG"},
        SYG12MC =   {ID = "ri3086_Inventory",   Name = "SYG-12 - Mercenaries",          Type = "SG"},
        F2MC    =   {ID = "ri3087_Inventory",   Name = "F2 Rifle - Mercenaries",        Type = "SR"},
        DRGOOMC =   {ID = "ri3129_Inventory",   Name = "Dragoon - Mercenaries",         Type = "AR"},
        USMAIMC =   {ID = "ri3130_Inventory",   Name = "USM-AI - Mercenaries",          Type = "HG"},
    },
    Weapon_Params = {
        ri3008_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 200.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 2,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 1700.0,
                    burstSpeed = 1.5,
                    chargeSpeed = 2.5,
                    countOfMaxStackSize = 5,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.07,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 120000,
                    SellPrice = 60000,
                    SellFullPrice = 427500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 1700.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.50,  Cost = 0},
                LVL1_RS     =   {Value = 2.50,  Cost = 0},
                LVL1_AC     =   {Value = 5,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 1900.0, Cost = 48000},
                LVL2_ROF    =   {Value = 1.40,  Cost = 21000},
                LVL2_RS     =   {Value = 2.40,  Cost = 18000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 2100.0, Cost = 65000},
                LVL3_ROF    =   {Value = 1.30,  Cost = 33000},
                LVL3_RS     =   {Value = 2.30,  Cost = 24000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 2300.0, Cost = 80000},
                LVL4_ROF    =   {Value = 1.20,  Cost = 44000},
                LVL4_RS     =   {Value = 2.20,  Cost = 38000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 2500.0, Cost = 100000},
                LVL5_ROF    =   {Value = 1.10,  Cost = 61000},
                LVL5_RS     =   {Value = 2.10,  Cost = 54000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 2700.0, Cost = 130000},
                LVL6_ROF    =   {Value = 1.00,  Cost = 82000},
                LVL6_RS     =   {Value = 2.00,  Cost = 75000},
            },
        },
        ri3021_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = -0.2,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 760.0,
                    burstSpeed = 1.6,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 4,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 3.0,
                    AttenuationStunStart = 3.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.17,
                    RecoilXAngle = 0.5,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 68000,
                    SellPrice = 34000,
                    SellFullPrice = 155000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 760.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.60,  Cost = 0},
                LVL1_RS     =   {Value = 2.70,  Cost = 0},
                LVL1_AC     =   {Value = 4,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 840.0, Cost = 16000},
                LVL2_RS     =   {Value = 2.50,  Cost = 8000},
                LVL2_AC     =   {Value = 6.0,  Cost = 11000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 960.0, Cost = 27000},
                LVL3_RS     =   {Value = 2.30,  Cost = 15000},
                LVL3_AC     =   {Value = 8.0,  Cost = 18000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 1120.0, Cost = 39000},
                LVL4_RS     =   {Value = 2.10,  Cost = 23000},
                LVL4_AC     =   {Value = 10.0,  Cost = 29000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1280.0, Cost = 53000},
                LVL5_RS     =   {Value = 1.90,  Cost = 34000},
                LVL5_AC     =   {Value = 12.0,  Cost = 41000},
            },
        },
        ri3023_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 1200.0,
                    burstSpeed = 0.45,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 1,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 12.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.05,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.5,
                    RecoilYAngle = 0.7,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 0.7,
                },
                Trade = {
                    UsedPrice = 100000,
                    SellPrice = 50000,
                    SellFullPrice = 100000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 1200.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.45,  Cost = 0},
                LVL1_RS     =   {Value = 2.70,  Cost = 0},
                LVL1_AC     =   {Value = 1,     Cost = 0},
            },
        },
        ri3036_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = -0.2,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 560.0,
                    burstSpeed = 1.7,
                    chargeSpeed = 2.8,
                    countOfMaxStackSize = 5,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.15,
                    RecoilXAngle = 0.2,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 24000,
                    SellPrice = 12000,
                    SellFullPrice = 36000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 560.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.70,  Cost = 0},
                LVL1_RS     =   {Value = 2.80,  Cost = 0},
                LVL1_AC     =   {Value = 5,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 640.0, Cost = 8000},
                LVL2_RS     =   {Value = 2.60,  Cost = 4000},
                LVL2_AC     =   {Value = 7.0,   Cost = 6000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 720.0, Cost = 10000},
                LVL3_RS     =   {Value = 2.40,  Cost = 7000},
                LVL3_AC     =   {Value = 9.0,   Cost = 9000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 800.0, Cost = 14000},
                LVL4_RS     =   {Value = 2.20,  Cost = 10000},
                LVL4_AC     =   {Value = 11.0,  Cost = 12000},
            },
        },
        ri3040_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 8,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 160.0,
                    burstSpeed = 0.27,
                    chargeSpeed = 2.9,
                    countOfMaxStackSize = 7,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.3,
                    RecoilBurstInterval = 0.4,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 50000,
                    SellPrice = 25000,
                    SellFullPrice = 112250,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 160.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.27,  Cost = 0},
                LVL1_RS     =   {Value = 2.90,  Cost = 0},
                LVL1_AC     =   {Value = 7,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 170.0, Cost = 10000},
                LVL2_ROF    =   {Value = 0.26,  Cost = 5000},
                LVL2_RS     =   {Value = 2.70,  Cost = 3500},
                LVL2_AC     =   {Value = 9.0,   Cost = 6000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 180.0, Cost = 17000},
                LVL3_ROF    =   {Value = 0.24,  Cost = 9000},
                LVL3_RS     =   {Value = 2.50,  Cost = 8000},
                LVL3_AC     =   {Value = 11.0,  Cost = 11000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 190.0, Cost = 26000},
                LVL4_ROF    =   {Value = 0.22,  Cost = 15000},
                LVL4_RS     =   {Value = 2.30,  Cost = 12000},
                LVL4_AC     =   {Value = 13.0,  Cost = 18000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 195.0, Cost = 40000},
                LVL5_ROF    =   {Value = 0.20,  Cost = 21000},
                LVL5_RS     =   {Value = 2.00,  Cost = 19000},
                LVL5_AC     =   {Value = 15.0,  Cost = 25000},
            },
        },
        ri3042_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 5,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 600.0,
                    burstSpeed = 2.0,
                    chargeSpeed = 3.7,
                    countOfMaxStackSize = 4,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 50.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.3,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.7,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 8.0,
                },
                Trade = {
                    UsedPrice = 40000,
                    SellPrice = 20000,
                    SellFullPrice = 240250,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 600.0, Cost = 0},
                LVL1_ROF    =   {Value = 2.0,  Cost = 0},
                LVL1_RS     =   {Value = 3.70,  Cost = 0},
                LVL1_AC     =   {Value = 4,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 700.0, Cost = 9000},
                LVL2_ROF    =   {Value = 1.80,  Cost = 4000},
                LVL2_RS     =   {Value = 3.50,  Cost = 5500},
                LVL2_AC     =   {Value = 6.00,  Cost = 7000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 850.0, Cost = 15000},
                LVL3_ROF    =   {Value = 1.70,  Cost = 8000},
                LVL3_RS     =   {Value = 3.30,  Cost = 10000},
                LVL3_AC     =   {Value = 8.00,  Cost = 11000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 1000.0, Cost = 29000},
                LVL4_ROF    =   {Value = 1.60,  Cost = 17000},
                LVL4_RS     =   {Value = 3.10,  Cost = 21000},
                LVL4_AC     =   {Value = 10.0,  Cost = 23000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1200.0, Cost = 41000},
                LVL5_ROF    =   {Value = 1.40,  Cost = 26000},
                LVL5_RS     =   {Value = 2.90,  Cost = 33000},
                LVL5_AC     =   {Value = 12.0,  Cost = 35000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 1500.0, Cost = 60000},
                LVL6_ROF    =   {Value = 1.20,  Cost = 39000},
                LVL6_RS     =   {Value = 2.70,  Cost = 45000},
                LVL6_AC     =   {Value = 15.0,  Cost = 50000},
            },
        },
        ri3046_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 30.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 6,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 100.0,
                    burstSpeed = 0.45,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 16000,
                    SellPrice = 8000,
                    SellFullPrice = 28250,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 100.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.45,  Cost = 0},
                LVL1_RS     =   {Value = 2.70,  Cost = 0},
                LVL1_AC     =   {Value = 10,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 110.0, Cost = 6000},
                LVL2_ROF    =   {Value = 0.42,  Cost = 3000},
                LVL2_RS     =   {Value = 2.50,  Cost = 2500},
                LVL2_AC     =   {Value = 12.0,  Cost = 4000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 120.0, Cost = 9000},
                LVL3_ROF    =   {Value = 0.39,  Cost = 5000},
                LVL3_RS     =   {Value = 2.30,  Cost = 4000},
                LVL3_AC     =   {Value = 14.0,  Cost = 6000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 130.0, Cost = 12000},
                LVL4_ROF    =   {Value = 0.36,  Cost = 8000},
                LVL4_RS     =   {Value = 2.20,  Cost = 7000},
                LVL4_AC     =   {Value = 16.0,  Cost = 10000},
            },
        },
        ri3047_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 25.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 30,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 200.0,
                    burstSpeed = 0.38,
                    chargeSpeed = 3.0,
                    countOfMaxStackSize = 12,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.5,
                    RecoilYAngle = 0.5,
                    RecoilBurstInterval = 0.4,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 120000,
                    SellPrice = 60000,
                    SellFullPrice = 565000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 200.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.38,  Cost = 0},
                LVL1_RS     =   {Value = 3.0,  Cost = 0},
                LVL1_AC     =   {Value = 12,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 210.0, Cost = 50000},
                LVL2_ROF    =   {Value = 0.34,  Cost = 22000},
                LVL2_RS     =   {Value = 2.70,  Cost = 17000},
                LVL2_AC     =   {Value = 15.0,  Cost = 30000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 220.0, Cost = 65000},
                LVL3_ROF    =   {Value = 0.30,  Cost = 31000},
                LVL3_RS     =   {Value = 2.40,  Cost = 26000},
                LVL3_AC     =   {Value = 18.0,  Cost = 42000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 230.0, Cost = 80000},
                LVL4_ROF    =   {Value = 0.25,  Cost = 44000},
                LVL4_RS     =   {Value = 2.20,  Cost = 38000},
                LVL4_AC     =   {Value = 21.0,  Cost = 55000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 240.0, Cost = 98000},
                LVL5_ROF    =   {Value = 0.20,  Cost = 58000},
                LVL5_RS     =   {Value = 2.00,  Cost = 51000},
                LVL5_AC     =   {Value = 24.0,  Cost = 68000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 250.0, Cost = 120000},
                LVL6_ROF    =   {Value = 0.15,  Cost = 70000},
                LVL6_RS     =   {Value = 1.80,  Cost = 64000},
                LVL6_AC     =   {Value = 27.0,  Cost = 80000},
            },
        },
        ri3048_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 80.0,
                    CustomROF = -0.05,
                    CustomRS  = 0.0,
                    CustomAC  = 20,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 1160.0,
                    burstSpeed = 1.4,
                    chargeSpeed = 3.5,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 3.0,
                    AttenuationStunStart = 3.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.120,
                    RecoilXAngle = 0.2,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 190000,
                    SellPrice = 90000,
                    SellFullPrice = 650500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 1160.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.4,  Cost = 0},
                LVL1_RS     =   {Value = 3.5,  Cost = 0},
                LVL1_AC     =   {Value = 10,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 1240.0, Cost = 65000},
                LVL2_RS     =   {Value = 3.20,  Cost = 20000},
                LVL2_AC     =   {Value = 12.0,  Cost = 37000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 1320.0, Cost = 79000},
                LVL3_RS     =   {Value = 2.90,  Cost = 31000},
                LVL3_AC     =   {Value = 14.0,  Cost = 49000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 1400.0, Cost = 91000},
                LVL4_RS     =   {Value = 2.60,  Cost = 45000},
                LVL4_AC     =   {Value = 16.0,  Cost = 61000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1520.0, Cost = 110000},
                LVL5_RS     =   {Value = 2.30,  Cost = 58000},
                LVL5_AC     =   {Value = 18.0,  Cost = 74000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 1680.0, Cost = 135000},
                LVL6_RS     =   {Value = 2.00,  Cost = 72000},
                LVL6_AC     =   {Value = 20.0,  Cost = 90000},
            },
        },
        ri3049_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 30.0,
                    CustomROF = -0.05,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 250.0,
                    burstSpeed = 0.15,
                    chargeSpeed = 3.2,
                    countOfMaxStackSize = 20,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.07,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.4,
                    RecoilBurstInterval = 0.3,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 200,
                    SellPrice = 50,
                    SellFullPrice = 350050,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 250.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.15,  Cost = 0},
                LVL1_RS     =   {Value = 3.2,  Cost = 0},
                LVL1_AC     =   {Value = 20,     Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 270.0, Cost = 43000},
                LVL2_RS     =   {Value = 3.10,  Cost = 28000},
                LVL2_AC     =   {Value = 30.0,  Cost = 20000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 290.0, Cost = 58000},
                LVL3_RS     =   {Value = 3.00,  Cost = 40000},
                LVL3_AC     =   {Value = 40.0,  Cost = 29000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 310.0, Cost = 72000},
                LVL4_RS     =   {Value = 2.90,  Cost = 53000},
                LVL4_AC     =   {Value = 50.0,  Cost = 42000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 340.0, Cost = 86000},
                LVL5_RS     =   {Value = 2.80,  Cost = 66000},
                LVL5_AC     =   {Value = 60.0,  Cost = 56000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 370.0, Cost = 103000},
                LVL6_RS     =   {Value = 2.60,  Cost = 78000},
                LVL6_AC     =   {Value = 80.0,  Cost = 68000},
            },
        },
        ri3050_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 8,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 2000.0,
                    burstSpeed = 1.3,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.07,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 300000,
                    SellPrice = 150000,
                    SellFullPrice = 898500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 2000.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.3,   Cost = 0},
                LVL1_RS     =   {Value = 2.7,   Cost = 0},
                LVL1_AC     =   {Value = 10,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 2500.0, Cost = 83000},
                LVL2_ROF    =   {Value = 1.20,  Cost = 30000},
                LVL2_RS     =   {Value = 2.50,  Cost = 33000},
                LVL2_AC     =   {Value = 12.0,  Cost = 40000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 3000.0, Cost = 96000},
                LVL3_ROF    =   {Value = 1.10,  Cost = 36000},
                LVL3_RS     =   {Value = 2.10,  Cost = 42000},
                LVL3_AC     =   {Value = 14.0,  Cost = 55000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 3500.0, Cost = 119000},
                LVL4_ROF    =   {Value = 1.00,  Cost = 53000},
                LVL4_RS     =   {Value = 2.10,  Cost = 56000},
                LVL4_AC     =   {Value = 16.0,  Cost = 68000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 4000.0, Cost = 140000},
                LVL5_ROF    =   {Value = 0.90,  Cost = 67000},
                LVL5_RS     =   {Value = 1.90,  Cost = 70000},
                LVL5_AC     =   {Value = 18.0,  Cost = 85000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 4500.0, Cost = 160000},
                LVL6_ROF    =   {Value = 0.80,  Cost = 82000},
                LVL6_RS     =   {Value = 1.70,  Cost = 85000},
                LVL6_AC     =   {Value = 20.0,  Cost = 100000},
            },
        },
        ri3081_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 75.0,
                    burstSpeed = 0.45,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 5000,
                    SellPrice = 2500,
                    SellFullPrice = 2500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 75.0,  Cost = 0},
                LVL1_ROF    =   {Value = 0.45,  Cost = 0},
                LVL1_RS     =   {Value = 2.7,   Cost = 0},
                LVL1_AC     =   {Value = 10,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 84.0,  Cost = 5000},
                LVL2_ROF    =   {Value = 0.35,  Cost = 3000},
                LVL2_RS     =   {Value = 1.80,  Cost = 3000},
                LVL2_AC     =   {Value = 15.0,  Cost = 3000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 98.0,  Cost = 5500},
                LVL3_ROF    =   {Value = 0.25,  Cost = 4000},
                LVL3_RS     =   {Value = 0.90,  Cost = 4000},
                LVL3_AC     =   {Value = 20.0,  Cost = 4000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 112.0, Cost = 6500},
                LVL4_AC     =   {Value = 25.0,  Cost = 5000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 126.0, Cost = 8000},
                LVL5_AC     =   {Value = 30.0,  Cost = 6000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 140.0, Cost = 10000},
                LVL6_AC     =   {Value = 35.0,  Cost = 7000},
            },
        },
        ri3082_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 95.0,
                    burstSpeed = 0.3,
                    chargeSpeed = 2.9,
                    countOfMaxStackSize = 20,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.3,
                    RecoilBurstInterval = 0.3,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 15000,
                    SellPrice = 7500,
                    SellFullPrice = 7500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 95.0,  Cost = 0},
                LVL1_ROF    =   {Value = 0.3,   Cost = 0},
                LVL1_RS     =   {Value = 2.9,   Cost = 0},
                LVL1_AC     =   {Value = 20,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 109.0, Cost = 6000},
                LVL2_ROF    =   {Value = 0.22,  Cost = 4000},
                LVL2_RS     =   {Value = 2.14,  Cost = 4000},
                LVL2_AC     =   {Value = 30.0,  Cost = 4000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 124.0, Cost = 6500},
                LVL3_ROF    =   {Value = 0.14,  Cost = 5000},
                LVL3_RS     =   {Value = 1.38,  Cost = 5000},
                LVL3_AC     =   {Value = 40.0,  Cost = 5000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 138.0, Cost = 7500},
                LVL4_AC     =   {Value = 50.0,  Cost = 6000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 152.0, Cost = 9000},
                LVL5_AC     =   {Value = 60.0,  Cost = 7000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 166.0, Cost = 11000},
                LVL6_AC     =   {Value = 70.0,  Cost = 8000},
            },
        },
        ri3083_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 120.0,
                    burstSpeed = 0.2,
                    chargeSpeed = 3.5,
                    countOfMaxStackSize = 12,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.3,
                    RecoilBurstInterval = 0.3,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 30000,
                    SellPrice = 15000,
                    SellFullPrice = 15000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 120.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.2,   Cost = 0},
                LVL1_RS     =   {Value = 3.5,   Cost = 0},
                LVL1_AC     =   {Value = 12,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 144.0, Cost = 7000},
                LVL2_ROF    =   {Value = 0.15,  Cost = 5000},
                LVL2_RS     =   {Value = 2.70,  Cost = 5000},
                LVL2_AC     =   {Value = 16.0,  Cost = 5000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 168.0, Cost = 7500},
                LVL3_ROF    =   {Value = 0.10,  Cost = 6000},
                LVL3_RS     =   {Value = 1.90,  Cost = 6000},
                LVL3_AC     =   {Value = 20.0,  Cost = 6000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 192.0, Cost = 8500},
                LVL4_AC     =   {Value = 24.0,  Cost = 7000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 216.0, Cost = 10000},
                LVL5_AC     =   {Value = 28.0,  Cost = 8000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 240.0, Cost = 12000},
                LVL6_AC     =   {Value = 32.0,  Cost = 9000},
            },
        },
        ri3084_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 620.0,
                    burstSpeed = 1.7,
                    chargeSpeed = 2.8,
                    countOfMaxStackSize = 5,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.15,
                    RecoilXAngle = 0.2,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 10000,
                    SellPrice = 5000,
                    SellFullPrice = 5000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 620.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.7,   Cost = 0},
                LVL1_RS     =   {Value = 2.8,   Cost = 0},
                LVL1_AC     =   {Value = 5,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 744.0, Cost = 6000},
                LVL2_ROF    =   {Value = 1.42,  Cost = 4000},
                LVL2_RS     =   {Value = 2.20,  Cost = 4000},
                LVL2_AC     =   {Value = 8.0,   Cost = 4000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 868.0, Cost = 6500},
                LVL3_ROF    =   {Value = 1.14,  Cost = 5000},
                LVL3_RS     =   {Value = 1.60,  Cost = 5000},
                LVL3_AC     =   {Value = 11.0,  Cost = 5000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 992.0, Cost = 7500},
                LVL4_AC     =   {Value = 14.0,  Cost = 6000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1116.0,Cost = 9000},
                LVL5_AC     =   {Value = 17.0,  Cost = 7000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 1240.0, Cost = 11000},
                LVL6_AC     =   {Value = 20.0,   Cost = 8000},
            },
        },
        ri3085_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 950.0,
                    burstSpeed = 0.72,
                    chargeSpeed = 2.5,
                    countOfMaxStackSize = 2,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 3.0,
                    AttenuationStunStart = 3.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.17,
                    RecoilXAngle = 0.5,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 20000,
                    SellPrice = 10000,
                    SellFullPrice = 10000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 950.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.72,   Cost = 0},
                LVL1_RS     =   {Value = 2.5,   Cost = 0},
                LVL1_AC     =   {Value = 2,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 1144.0,Cost = 7000},
                LVL2_ROF    =   {Value = 0.56,  Cost = 5000},
                LVL2_RS     =   {Value = 1.90,  Cost = 5000},
                LVL2_AC     =   {Value = 3.0,   Cost = 5000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 1330.0,Cost = 7500},
                LVL3_ROF    =   {Value = 0.40,  Cost = 6000},
                LVL3_RS     =   {Value = 1.30,  Cost = 6000},
                LVL3_AC     =   {Value = 4.0,   Cost = 6000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 1520.0, Cost = 8500},
                LVL4_AC     =   {Value = 5.0,    Cost = 7000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1710.0,Cost = 10000},
                LVL5_AC     =   {Value = 6.0,   Cost = 8000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 1900.0, Cost = 12000},
                LVL6_AC     =   {Value = 7.0,    Cost = 9000},
            },
        },
        ri3086_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 1160.0,
                    burstSpeed = 2.2,
                    chargeSpeed = 3.5,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 3.0,
                    AttenuationStunStart = 3.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.120,
                    RecoilXAngle = 0.2,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 30000,
                    SellPrice = 15000,
                    SellFullPrice = 15000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 1160.0, Cost = 0},
                LVL1_ROF    =   {Value = 2.2,   Cost = 0},
                LVL1_RS     =   {Value = 3.5,   Cost = 0},
                LVL1_AC     =   {Value = 10,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 1392.0,Cost = 8000},
                LVL2_ROF    =   {Value = 1.80,  Cost = 6000},
                LVL2_RS     =   {Value = 2.90,  Cost = 6000},
                LVL2_AC     =   {Value = 15.0,  Cost = 6000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 1624.0,Cost = 8500},
                LVL3_ROF    =   {Value = 1.40,  Cost = 7000},
                LVL3_RS     =   {Value = 2.30,  Cost = 7000},
                LVL3_AC     =   {Value = 20.0,  Cost = 7000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 1856.0, Cost = 9500},
                LVL4_AC     =   {Value = 25.0,   Cost = 8000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 2088.0,Cost = 11000},
                LVL5_AC     =   {Value = 30.0,  Cost = 9000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 2320.0, Cost = 13000},
                LVL6_AC     =   {Value = 35.0,   Cost = 10000},
            },
        },
        ri3087_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 600.0,
                    burstSpeed = 2.0,
                    chargeSpeed = 3.7,
                    countOfMaxStackSize = 4,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 50.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.3,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.7,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 8.0,
                },
                Trade = {
                    UsedPrice = 15000,
                    SellPrice = 7500,
                    SellFullPrice = 7500,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 600.0, Cost = 0},
                LVL1_ROF    =   {Value = 2.0,   Cost = 0},
                LVL1_RS     =   {Value = 3.7,   Cost = 0},
                LVL1_AC     =   {Value = 4,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 720.0, Cost = 7500},
                LVL2_ROF    =   {Value = 1.60,  Cost = 5500},
                LVL2_RS     =   {Value = 2.90,  Cost = 5500},
                LVL2_AC     =   {Value = 7.0,   Cost = 5500},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 840.0, Cost = 8000},
                LVL3_ROF    =   {Value = 1.20,  Cost = 6500},
                LVL3_RS     =   {Value = 2.10,  Cost = 6500},
                LVL3_AC     =   {Value = 10.0,  Cost = 6500},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 960.0,  Cost = 9000},
                LVL4_AC     =   {Value = 13.0,   Cost = 7500},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 1080.0,Cost = 10500},
                LVL5_AC     =   {Value = 16.0,  Cost = 8500},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 1200.0, Cost = 12500},
                LVL6_AC     =   {Value = 19.0,   Cost = 9500},
            },
        },
        ri3115_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 550.0,
                    burstSpeed = 1.1,
                    chargeSpeed = 3.7,
                    countOfMaxStackSize = 7,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 100.0,
                    AttenuationStunStart = 100.0,
                    Radius = 0.0,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 0.7,
                },
                Trade = {
                    UsedPrice = 1500,
                    SellPrice = 100,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 550.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.1,   Cost = 0},
                LVL1_RS     =   {Value = 3.7,   Cost = 0},
                LVL1_AC     =   {Value = 7,    Cost = 0},
            },
        },
        ri3116_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 1400.0,
                    burstSpeed = 1.6,
                    chargeSpeed = 2.8,
                    countOfMaxStackSize = 5,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 50.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.0,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 1100,
                    SellPrice = 100,
                    SellFullPrice = 1100,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 1400.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.6,   Cost = 0},
                LVL1_RS     =   {Value = 2.8,   Cost = 0},
                LVL1_AC     =   {Value = 5,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 1600.0, Cost = 68000},
                LVL2_ROF    =   {Value = 1.50,  Cost = 25000},
                LVL2_RS     =   {Value = 2.80,  Cost = 28000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 1900.0, Cost = 81000},
                LVL3_ROF    =   {Value = 1.40,  Cost = 34000},
                LVL3_RS     =   {Value = 1.30,  Cost = 37000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 2300.0, Cost = 94000},
                LVL4_ROF    =   {Value = 1.30,  Cost = 48000},
                LVL4_RS     =   {Value = 2.20,  Cost = 51000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 2700.0, Cost = 115000},
                LVL5_ROF    =   {Value = 1.10,  Cost = 62000},
                LVL5_RS     =   {Value = 2.00,  Cost = 65000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 3200.0, Cost = 140000},
                LVL6_ROF    =   {Value = 0.90,  Cost = 77000},
                LVL6_RS     =   {Value = 1.80,  Cost = 80000},
            },
        },
        ri3122_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 110.0,
                    burstSpeed = 0.4,
                    chargeSpeed = 2.6,
                    countOfMaxStackSize = 9,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.0,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 350,
                    SellPrice = 50,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 110.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.4,   Cost = 0},
                LVL1_RS     =   {Value = 2.6,   Cost = 0},
                LVL1_AC     =   {Value = 9,    Cost = 0},
            },
        },
        ri3124_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 270.0,
                    burstSpeed = 0.13,
                    chargeSpeed = 2.5,
                    countOfMaxStackSize = 17,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.0,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 350,
                    SellPrice = 50,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 270.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.13,   Cost = 0},
                LVL1_RS     =   {Value = 2.5,   Cost = 0},
                LVL1_AC     =   {Value = 17,    Cost = 0},
            },
        },
        ri3125_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 350.0,
                    burstSpeed = 0.11,
                    chargeSpeed = 2.9,
                    countOfMaxStackSize = 30,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.07,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.4,
                    RecoilBurstInterval = 0.3,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 400,
                    SellPrice = 10,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 350.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.11,   Cost = 0},
                LVL1_RS     =   {Value = 2.9,   Cost = 0},
                LVL1_AC     =   {Value = 30,    Cost = 0},
            },
        },
        ri3129_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 125.0,
                    burstSpeed = 0.1,
                    chargeSpeed = 2.9,
                    countOfMaxStackSize = 35,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 150.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.07,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.3,
                    RecoilYAngle = 0.4,
                    RecoilBurstInterval = 0.3,
                    RecoilBurstCount = 1,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 25000,
                    SellPrice = 5000,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 125.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.1,   Cost = 0},
                LVL1_RS     =   {Value = 2.9,   Cost = 0},
                LVL1_AC     =   {Value = 35,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 160.0, Cost = 8500},
                LVL2_RS     =   {Value = 2.50,  Cost = 5000},
                LVL2_AC     =   {Value = 65.0,  Cost = 9500},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 195.0, Cost = 12000},
                LVL3_RS     =   {Value = 2.10,  Cost = 6500},
                LVL3_AC     =   {Value = 100.0, Cost = 120000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 230.0,  Cost = 15500},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 500.0, Cost = 30000},
            },
        },
        ri3130_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = true,
                Params = {
                    power = 210.0,
                    burstSpeed = 0.45,
                    chargeSpeed = 2.5,
                    countOfMaxStackSize = 17,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 500.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.0,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 9000,
                    SellPrice = 4500,
                    SellFullPrice = 0,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 210.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.45,   Cost = 0},
                LVL1_RS     =   {Value = 2.5,   Cost = 0},
                LVL1_AC     =   {Value = 17,    Cost = 0},
            },
            Level_2 = {
                LVL2_DMG    =   {Value = 235.0, Cost = 5000},
                LVL2_ROF    =   {Value = 0.35,  Cost = 3000},
                LVL2_RS     =   {Value = 1.80,  Cost = 3000},
                LVL2_AC     =   {Value = 21.0,  Cost = 3000},
            },
            Level_3 = {
                LVL3_DMG    =   {Value = 260.0, Cost = 5500},
                LVL3_ROF    =   {Value = 0.25,  Cost = 4000},
                LVL3_RS     =   {Value = 1.10,  Cost = 4000},
                LVL3_AC     =   {Value = 25.0,  Cost = 4000},
            },
            Level_4 = {
                LVL4_DMG    =   {Value = 285.0,  Cost = 6500},
                LVL4_AC     =   {Value = 29.0,   Cost = 5000},
            },
            Level_5 = {
                LVL5_DMG    =   {Value = 310.0, Cost = 8000},
                LVL5_AC     =   {Value = 33.0,  Cost = 6000},
            },
            Level_6 = {
                LVL6_DMG    =   {Value = 335.0,  Cost = 10000},
                LVL6_AC     =   {Value = 37.0,   Cost = 7000},
            },
        },
        ri3135_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 26.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 6,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                   power = 100.0,
                    burstSpeed = 0.6,
                    chargeSpeed = 2.7,
                    countOfMaxStackSize = 10,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 100.0,
                    AttenuationStart = 10.0,
                    AttenuationStunStart = 10.0,
                    Radius = 0.06,
                    IsDiffusion = false,
                    DiffusionNum = 1,
                    DiffusionRadius = 0.0,
                    RecoilXAngle = 0.0,
                    RecoilYAngle = 0.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 3,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 16000,
                    SellPrice = 8000,
                    SellFullPrice = 28250,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 100.0, Cost = 0},
                LVL1_ROF    =   {Value = 0.6,   Cost = 0},
                LVL1_RS     =   {Value = 2.7,   Cost = 0},
                LVL1_AC     =   {Value = 10,    Cost = 0},
            },
        },
        ri3147_Inventory = {
            Weapon_Presets = {},
            current_param_indx = 1,
            Level_DMG = 0,
            Level_ROF = 0,
            Level_RS = 0,
            Level_AC = 0,
            CurrentStats = {
                DMG = 0.0,
                ROF = 0.0,
                RS = 0.0,
                AC = 0,
            },
            CustomParts = {
                customizeMagazine = false,
                customizeGrip = false,
                customizeBarrel = false,
                cuztomizeStock = false,
                CustomStats = {
                    CustomDMG = 0.0,
                    CustomROF = 0.0,
                    CustomRS  = 0.0,
                    CustomAC  = 0,
                },
            },
            BaseStats = {
                stunRate = 1.0,
                isPenetration = false,
                Params = {
                    power = 560.0,
                    burstSpeed = 1.7,
                    chargeSpeed = 2.8,
                    countOfMaxStackSize = 5,
                    optionPower = 0.0,
                    optionBurstSpeed = 0.0,
                    optionChargeSpeed = 0.0,
                    countOfOptionMaxStackSize = 0,
                },
                GunSpecs = {
                    Range = 30.0,
                    AttenuationStart = 30.0,
                    AttenuationStunStart = 30.0,
                    Radius = 0.05,
                    IsDiffusion = true,
                    DiffusionNum = 8,
                    DiffusionRadius = 0.15,
                    RecoilXAngle = 0.2,
                    RecoilYAngle = 2.0,
                    RecoilBurstInterval = 0.1,
                    RecoilBurstCount = 0,
                    DistancePerFrame = 5.0,
                },
                Trade = {
                    UsedPrice = 24000,
                    SellPrice = 12000,
                    SellFullPrice = 36000,
                },
            },
            Level_1 = {
                LVL1_DMG    =   {Value = 560.0, Cost = 0},
                LVL1_ROF    =   {Value = 1.7,   Cost = 0},
                LVL1_RS     =   {Value = 2.8,   Cost = 0},
                LVL1_AC     =   {Value = 5,    Cost = 0},
            },
        },
    },
    Weapon_Order = {
        "LEMI",
        "M1911",
        "V61",
        "USMAI",
        "GYRO",
        "AW01",
        "M1851",
        "STK",
        "HCPZ",
        "M1897",
        "W870",
        "SYG12",
        "F2",
        "WCX",
        "DRGOO",
        "GM79",
        "LEMISOR",
        "M1897SOR",
        "LEMIMC",
        "M1911MC",
        "V61MC",
        "USMAIMC",
        "M1897MC",
        "W870MC",
        "SYG12MC",
        "F2MC",
        "DRGOOMC",
    },
}

return RE8_WeaponData